services:
    nginx:
        image: "nginx:stable-alpine"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/laravel
        ports:
            - "8080:80"
        depends_on:
            - php
            - mysql
    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        env_file:
            - env/mysql.env
        volumes:
            - db_data:/var/lib/mysql
    phpmyadmin:
        image: "phpmyadmin:latest"
        ports:
            - "8081:80"
        environment:
            PMA_HOST: "mysql"
            PMA_PORT: 3306
        depends_on:
            - mysql
    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - db_data:/var/www/laravel
    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel
        entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data: